### ISSUE TITLE
关于fancybox 的用法

### ISSUE THREAD

**Issue by xiezuan** [iTimeTraveler/hexo-theme-hipaper#1]
非常喜欢你的这个主题，感谢你的无私分享，我想问一下， fancybox 是指在主页列表里面显示一张预览图片吗？为什么我使用时总是自动显示图片呢？  下面这两句是写在正文的markdown 里面吗？我的使用方式好像不对。
![img caption](img url)
{% fancybox img_url [img_thumbnail] [img_caption] %}

**Comment by xiezuan** [comment]
列表显示的是自动的其它图片
![](http://ww2.sinaimg.cn/large/006tNbRwgw1fapnuxmqg6j314m0wqn3q.jpg)
我是这样写的
![](http://ww4.sinaimg.cn/large/006tNbRwgw1fapnwfdxynj31180a03zv.jpg)

正文里面是这样的
![](http://ww2.sinaimg.cn/large/006tNbRwgw1fapnxjbduqj314o0rkwkd.jpg)

**Comment by iTimeTraveler** [comment]
@xiezuan  其实fancybox我也理解了很长时间，但不是你说的那个。它是提供图片预览的，在文章正文页点击文章里的一个图，就会打开像下面这样预览（只是没有这么漂亮），左右键可以顺序查看。

![](https://camo.githubusercontent.com/e5f151115ba7c49b177c7be765783cc114006c46/687474703a2f2f70706f66666963652e6769746875622e696f2f6865786f2d7468656d652d6963617275732f67616c6c6572792f6c6967687467616c6c6572792e6a7067)


首页文章摘要列表页的图片展示和fancybox不是一回事。文章摘要图其实是markdown头部的一个photos字段，你可以参考一下我的文章源代码应该就懂了 https://github.com/iTimeTraveler/hexo-theme-hiero/tree/site-source

**Comment by xiezuan** [comment]
明白了，多谢！！
