### ISSUE TITLE
Header Meau 在生页面时 categories 栏目会显示出全大写的Kategorien而非大写的categories

### ISSUE THREAD

**Issue by ioiioo** [iTimeTraveler/hexo-theme-hipaper#11]
如题在主题配制文件 如下配制时:
```
> menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
rss: /atom.xml
```
使用 hexo g 命令生成的页面的导航栏应是 categories 链接,但却显示成了.Kategorien 

并且会出阅读每一篇文章时,会有与 about页面一样的大图产生. 这个大图不应是只有在about页面里面才会有的么?

![](http://i1.piimg.com/567571/ad175f6802d336f5.png)

**Comment by iTimeTraveler** [comment]
@ioiioo 头部菜单栏显示成Kategorien，是因为语言的配置问题，是Hexo根目录的`_config.yml`文件中的`language`字段

https://github.com/iTimeTraveler/hexo-theme-hiero/tree/site-source 这是我的Hexo源目录，你参考一下，顺便看下还会不会产生第二个问题（About页面大图的问题），前提先确认一下hipaper主题源码有没有被更改过，或者是不是最新版

**Comment by ioiioo** [comment]
thanks, 参考源目录,语言设置成 en之后,第一个问题不在复现. 
cd到主题目录, git pull 命令更新到最新之后, 
clean 并重新生成所有页面后,第二个 大图问题不在复现.

**Comment by iTimeTraveler** [comment]
好的 :+1:
