### ISSUE TITLE
请问作者如何修改或去掉页首图片

### ISSUE THREAD

**Issue by Von-Hyou** [iTimeTraveler/hexo-theme-hipaper#12]
![](https://ooo.0o0.ooo/2017/06/15/59427c57c88a1.png)

**Comment by iTimeTraveler** [comment]
Hello， @Von-Hyou 

### 1、不显示页首图片

你想要去掉不显示这个图片的话，可以直接在Hipaper主题文件夹下修改 `_config.yml` 中的以下配置：

```yml
# AboutPage background, support multiple images.
about_big_image: [css/images/pose01.jpg, https://images.unsplash.com/photo-1464306208223-e0b4495a5553?dpr=1&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop=&bg=]

```

直接去掉 `about_big_image` 这个字段之后的内容，像下面这样：

```yml
# AboutPage background, support multiple images.
about_big_image: 
```

### 2、修改页首图片

要是想直接修改页首图片的话，这部分代码在 `hipaper\layout\_partial` 文件夹下的 `header-post.ejs` 文件中。你可以在文件中查找关键词`if (is_current("about", false) && theme.about_big_image)` ，然后试着去掉这个if代码段看看

**Comment by Von-Hyou** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)十分感谢！
