### ISSUE TITLE
archives页面失效

### ISSUE THREAD

**Issue by icanfly** [iTimeTraveler/hexo-theme-hipaper#5]
比如在归档页面中点击“2015”并不会过滤到2015年的归档，同理在首页右下边的“archives”中，点击按月份的归档也并不会跳转到按月归档的界面上，而是显示的全部归档文章。

您的示例网站也是这样的，这是一个bug吗？

**Comment by iTimeTraveler** [comment]
@icanfly 恩，我试了一下好像确实是。周一我抽时间看看

**Comment by iTimeTraveler** [comment]
@icanfly  好了，你更新下代码再试试看
