### ISSUE TITLE
headerblur - cannot read property 'style' of null

### ISSUE THREAD

**Issue by llbarril** [iTimeTraveler/hexo-theme-hipaper#6]
Hello,

Looking at the devtools in chrome I've noticed the uncaught TypeError mentioned in the title gets thrown. It appears that the following piece of code located at _partial/footer triggers the error:

```
<!-- headerblur min height -->
    var headerblur = document.getElementById("header-blur");
    headerblur.style.minHeight = window.getComputedStyle(document.getElementById("allheader"), null).height;
```

I wonder if it would be safe to remove that code snippet from _partial/footer in order to prevent the error to appear in the devtools console. It seems that there is no html element with id #header-blur, hence the error.

**Comment by iTimeTraveler** [comment]
Hi, @llbarril  Sorry, I find it's a bug just now. and I have fixed it. You can just use **`git pull`** to update code and check it.

This code snippet will set min height for the big blur image in **`About Page`**. It just should have effect in About Page, but I made a mistake in forgetting to fliter this pages.

**Comment by llbarril** [comment]
Updated. No errors in the console now. Thanks!
