### ISSUE TITLE
Categories & Tags index pages not rendering

### ISSUE THREAD

**Issue by mvxt** [iTimeTraveler/hexo-theme-hipaper#8]
Hello,

I've been messing around with my settings for a while and for whatever reason, my blog framework doesn't render an index.html page for /categories and /tags. I do see that you have categories and tags defined in the layout, and the pages exist in your example blog.  Is there something I'm doing incorrectly?

"Cannot GET /categories/"

Thanks for your time.

**Comment by mvxt** [comment]
Nevermind, I answered my own question. I'm dumb. Sorry for the trouble!

**Comment by iTimeTraveler** [comment]
@mvxt  Hahaha，all right.

**Comment by kiarafrobles** [comment]
@mvxt I'm having the same problem. I'm not sure how to render the two pages from the generated markdown files. Can you explain?

**Comment by iTimeTraveler** [comment]
@kiarafrobles Hi，this is my demo site source: https://github.com/iTimeTraveler/hexo-theme-hiero/tree/site-source

Hope that source is helpful for you.

**Comment by mvxt** [comment]
@kiarafrobles Hey Kiara, check out the source code he provided as a reference, but basically you want to run `hexo new page [Categories|Tags]` and then in the source for those new pages, add a parameter at the top `layout: "categories"` or `layout: "tags"`. 

@iTimeTraveler Maybe we could add a wiki entry about this? It's been a few months now, but I think the way I found out was also by looking through the source of some of your public repositories.

**Comment by kiarafrobles** [comment]
Thanks @mvxt that worked for me!
